### ISSUE TITLE
[Tracking Issue] Update/extend the infra side to enable the support of the optimistic block finalities

### ISSUE THREAD

**Issue by khorolets** [near/read-rpc#200]
Once near/read-rpc#199 is done, we can spin up the ReadRPC service with the optimistic block finality support.

This issue aims to track the progress of the infra configuration updates.

## Plan

- [x] Update the infra configuration to include new service components:
  - [x] Minimal Redis instance
  - [x] `near-state-indexer`
    - [x] Packer image
    - [x] Terraform and Ansible scripts
- [x] Roll up the updated infra for the traffic mirroring/staging setup
- [x] Manually test and watch the logs to ensure everything works
- [ ] Roll up the updated infra for the production `testnet` setup
- [x] Roll up the updated infra for the production `mainnet` setup
```[tasklist]
### Tasks
```

**Comment by khorolets** [comment]
Packer image has been created https://github.com/PagodaPlatform/pkr-node/pull/32

**Comment by khorolets** [comment]
We've enabled the optimistic block finalities feature on the mirroring instance. We are waiting for @ecp88 to enable the traffic there and will monitor the charts to ensure the feature works as expected.
After that, we will proceed to enable the feature on the mainnet production instance of the ReadRPC 🤞
