### ISSUE TITLE
Improve or refactor the database crate to respect and follow the shard layout from `nearcore`

### ISSUE THREAD

**Issue by khorolets** [near/read-rpc#289]
As we decided, we want the `database` crate to be able to follow the shard layout from `nearcore`.

The NEAR Protocol has always up-to-date shard layout in the `ProtocolConfigView`, so it's better to rely on that. Also, it's not changing frequently and definitely this is not happening unnoticed.

```[tasklist]
### Tasks
- [x] `database` crate to follow the shard layout from `nearcore`
- [x] Adopt new design by `state-indexer`
- [x] Adopt new design by `tx-indexer`
- [x] Adopt new design by `rpc-server`
```
